### ISSUE TITLE
Add support for ES6 using Babel 

### ISSUE THREAD

**Issue by thejameskyle** [sindresorhus/generator-nm#10]
C'mon @sindresorhus, all the cool kids are doing it! You even belong to the Babel org!

More seriously though, I think it'd be really awesome to see more node modules like this using babel.

**Comment by sindresorhus** [comment]
Yeah, I know... It's just that I mostly do a lot of small modules and the overhead of adding a build step hasn't been worth the minor gain I get from ES6 yet. I use Babel in non-module things.

Happy to add a prompt and flag though. I'll try to get to this soon, but a PR will definitely make it happen faster.

-

Related https://github.com/yeoman/generator-node/pull/110/files

**Comment by thejameskyle** [comment]
I can make a PR

**Comment by montogeek** [comment]
nice

**Comment by arthurvr** [comment]
How would we like the build step? npm script? Gulp?

**Comment by thejameskyle** [comment]
Probably an `npm prepublish` and `npm test` script?

**Comment by sindresorhus** [comment]
Yup

**Comment by arthurvr** [comment]
:+1:

**Comment by u4q** [comment]
+1

**Comment by SamVerschueren** [comment]
Reopening it as the PR is not merged yet.

**Comment by thejameskyle** [comment]
I was closing it because its just been sitting here

**Comment by SamVerschueren** [comment]
There is clearly interest in it and a PR was already made so it's in the works. Should be closed when the PR gets merged ;).

**Comment by jamestalmage** [comment]
I would really like to see this happen. #47 is a possible solution, but it's been sitting dormant, I think maybe because we all still haven't decided on the best way to do things.

Specifically, I would like to settle the following items before asking for more modifications to that PR.

1. Directory Structure - it seems like there are two schools of thought:

  1. Raw code lives in the base directory (and `lib` if necessary). Those contents are transpiled into the `dist` directory when compiling via babel. 

    - **Pro:** Your editable sources stay in the base directory.
    - **Con:** Requires a non-default entry point in `package.json` (`main: 'dist/index.js'`).
    - **Con:** Submodules become tricky (`ava/api`, `any-observable/register`).  

  2. Raw code all lives in a `src` directory, and are transpiled to the base directory. This basically flips the Pro/Con list above:

    - **Con:** Your editable sources are in a subdirectory. The `index.js` in your base directory should not be edited. It's easy to mistakenly do so and have it overwritten the next time you run the babel build.
    - **Pro:** You can use the default entry point `index.js`.
    - **Pro:** Submodules just work.

2. Transpiling sources for testing.

  1. Use `ava --require babel-register`. This is darn simple, and probably the fastest for a single run. But it's likely to be a lot slower in watch mode because it loads `babel-register` in every fork.

  2. Use `babel-cli` to transpile before testing. This misses out on some of AVA's transform caching behavior, so likely slower for single runs.  For watch mode, it would mean running `babel --watch` and `ava --watch` in parallel. AVA would watch babels output dir for source changes.

3. What babel presets should we default to? 

  1. `es2015` is a given I think.
  2. Do we include `stage-3` for sources? It contains `async`/`await`, which is pretty important IMO. 
  3. Since `generator-nm` is focused on modules, I think `transform-runtime` is a given as well.
  4. Do we want to give them a prompt to choose their presets / plugins? I would prefer just providing a sensible default.

4. Publish step.

  1. Should we commit transpiled results? Practices vary.
  2. Should we use the `prepublish` sript, or the `version` script? (this will basically be decided by our decision in `4.i` - the `version` script allows you to add things to the commit).

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/generator-nm/pull/47#issuecomment-267771429
