### ISSUE TITLE
Could there be following options in generator prompt?

### ISSUE THREAD

**Issue by sarbbottam** [sindresorhus/generator-nm#54]
- spaces for indentation, defaults to `tab`
- enforce `es-next` in xo, defaults to `false`

**Comment by sindresorhus** [comment]
> spaces for indentation, defaults to tab

👎  This generator is just what I use. If we start introducing stuff like that everything get's complicated. Now we'll need to convert indentation for everything and stuff.

> enforce es-next in xo, defaults to false

I think we can just do it by default without a prompt. All my new Node.js modules target Node.js 4.

**Comment by sarbbottam** [comment]
>>enforce es-next in xo, defaults to false

>I think we can just do it by default without a prompt. All my new Node.js modules target Node.js 4.

Should I raise a PR?

**Comment by sholladay** [comment]
This issue can be closed. The `esnext` option was added in https://github.com/sindresorhus/generator-nm/commit/1f5ff89c082b8e070d025597a87adc96462f406e and [isn't even needed anymore](https://github.com/sindresorhus/generator-nm/commit/49bfe9265c44414a40469e9a93d8016095d95e31) because it is true by default in XO itself now.
